#!/bin/bash -xe

JAR=./target/scala-2.11/jenkins-forever-etl-shaded.jar

sbt assembly

spark-submit \
    --conf spark.hadoop.mapreduce.input.fileinputformat.input.dir.recursive=true \
    $JAR \
    $*
