#!/bin/bash -xe

JAR=./target/scala-2.11/jenkins-forever-etl-shaded.jar

[ -f $JAR ] || sbt assembly

spark-submit \
    --conf spark.hadoop.mapreduce.input.fileinputformat.input.dir.recursive=true \
    $JAR \
    -j src/test/resources \
    -o target/out
